package com.studystream.domain.security

enum class Permission(
    val privilegeName: String,
) {
    DEVICES_READ("READ_ALL_DEVICES"),

    ACCOUNTS_READ("READ_ACCOUNTS"),
    ACCOUNTS_CREATE("WRITE_ACCOUNTS"),
    ACCOUNTS_UPDATE("WRITE_ACCOUNTS"),
    ACCOUNTS_DELETE("DELETE_ACCOUNTS"),

    PROFILES_READ("READ_ALL_PROFILES"),
    PROFILES_CREATE("WRITE_PROFILES"),
    PROFILES_UPDATE("WRITE_PROFILES"),
    PROFILES_DELETE("DELETE_PROFILES"),

    TICKETS_READ("READ_ALL_TICKETS"),
    TICKETS_CREATE("WRITE_TICKETS"),
    TICKETS_UPDATE("WRITE_TICKETS"),
    TICKETS_DELETE("DELETE_TICKETS"),

//    TICKET_TYPES_READ("READ_ALL_TICKET_TYPES"),
    TICKET_TYPES_CREATE("WRITE_TICKET_TYPES"),
    TICKET_TYPES_UPDATE("WRITE_TICKET_TYPES"),
    TICKET_TYPES_DELETE("DELETE_TICKET_TYPES"),
}