services:
  database:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 25
    volumes:
      - ./database/logs:/logs
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  server:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: "jdbc:mysql://database:3306/$DATABASE_NAME"
