ktor:
  development: "$DEV:true"
  application:
    modules:
      - com.studystream.app.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    watch:
      - classes
      - resources

jwt:
  secret: "$JWT_SECRET"
  issuer: "$JWT_ISSUER"
  audience: "$JWT_AUDIENCE"
  realm: "$JWT_REALM"
  claimName: "username"
  ttl: "$JWT_TTL"

database:
  url: "$DATABASE_URL"
  user: "$DATABASE_USER"
  password: "$DATABASE_PASSWORD"
  poolSize: "$POOL_SIZE:6"

feature:
  refreshToken:
    tokenRefreshThreshold: 3600000

store:
  temp: "$TEMP_FILES_PATH"
  regular: "$FILE_STORE_PATH"
  namingPattern: "{FILE_NAME}_{FILE_HASH}_{TIMESTAMP}_.{EXTENSION}"
  maxFilenameLength: 255
