name: Clear old runs

on:
  push:
    branches:
      - "main"
      - "develop"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ GITHUB_REPOSITORY }}
          older-than-seconds: 2592000 # 30 days
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
