name: Clear old runs

on:
  push:
    branches:
      - "main"
      - "develop"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.3.0
        with:
          with-owner: 'true'

      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ steps.repo-name.outputs.repository-name }}
          older-than-seconds: 2592000 # 30 days
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
