name: Server Actions

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  check-tests-need:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files: |
            **.gradle
            gradle.properties
            buildSrc/**
            server/**
            shared/**

      - name: Check any server files changed
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "No files changed in server"
          exit 0
  build:
    runs-on: ubuntu-latest
    needs:
      - check-tests-need
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build
        run: ./gradlew build
  tests:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Run tests
        run: ./gradlew test
