name: Deploy to Dev server

on:
  push:
    branches:
      - "develop"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: "Check Dockerfile existence"
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "server/Dockerfile"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo "Not all files required for deployment are found in the repository"
          exit 1

      - uses: chrnorm/deployment-action@v2
        name: Create deployment
        id: deployment
        with:
          token: '${{ github.token }}'

      - name: Deploy dev
        id: run_deploy
        uses: JorgeLNJunior/render-deploy@v1.4.4
        continue-on-error: true
        with:
          service_id: ${{ secrets.DEV_SERVICE_ID }}
          api_key: ${{ secrets.API_KEY }}
          wait_deploy: true

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Update deployment status (success)
        if: steps.run_deploy.outcome == 'success'
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: steps.run_deploy.outcome != 'success'
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
